config/routes.rb
Rails.application.routes.draw do

  get 'compras/confirmar', to: 'compras#confirmar'

  get 'compras/agregar', to: 'compras#agregar'

  post 'reportes/enviar', to: 'reportes#enviar'

  resources :answers

  resources :compras

  resources :logros 

  resources :reportes

  get 'main/default'
  root to: 'favors#index'

  

  devise_for :usuarios, :controllers => { registrations: 'registrations' }

  resources :usuarios, :only => [:index, :show]
 

  resources :favors
   get '/gauchadas', to: 'favors#index'
   get '/gauchadas/:id', to: 'favors#show'

  resources :comentarios do
    member do
      post 'comentar/:gau_id', :action => 'comentar', :as => 'comentar'
    end
  end

  resources :postulacions

  get '/elegiruser', to: 'postulacions#elegir_usuario'
  get '/finalizar_gauchada', to: 'favors#finalizar_gauchada'
  get '/gauchada_resuelta', to: 'favors#gauchada_resuelta'
  get '/gauchada_no_resuelta', to: 'favors#gauchada_no_resuelta'
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def default
  	
  end
end

app/views/main/default.html.erb
<div class="border-list-div">
	<div style="overflow: auto;">
		<% if usuario_signed_in? %>
		<% nom = current_usuario.nombre.capitalize %> 
		<div style="float: left;">
			<h1> Bienvenido <%= nom %>!</h1>
		</div>
		
		<div style=" float: right; overflow: auto;">
			<%= image_tag "logo_sm_t.png", title:"logo", style: "max-height: 500px;"%>
		</div>
		
		<% else %>
		<h1> Bienvenido!</h1>
		<% end %>

	</div>

	<h3> ¿Que desea hacer? </h3>
	<br>
	<br>
		<div style="overflow: auto">
		<div style="float: left;margin-bottom: 4px;">
			<%= link_to "Listado de Gauchadas",gauchadas_path, class: 'btn btn-warning btn-lg' %>
		<% if usuario_es_admin? %>
			<%= link_to "Listado de Logros",logros_path, class: 'btn btn-warning btn-lg' %>
		<% end %>
		<hr/>
		<%if usuario_signed_in? %>
			<%= link_to "Tienda",compras_path, class: 'btn btn-warning btn-lg' %>
		<% end %>
		<!--
		</div>
		<div style="float: right;margin-bottom: 4px;">
			< % if usuario_signed_in? %>
			< %= link_to "Cerrar Sesion", destroy_usuario_session_path, :method => :delete, class: 'btn btn-danger btn-lg'%>
			< % else %>
			< %= link_to "Iniciar Sesion", new_usuario_session_path, class: 'btn btn-info btn-lg' %>
			< %= link_to "Registrarme", new_usuario_registration_path, class: 'btn btn-success btn-lg' %>
			< % end %>
		</div>
		</div>
		-->

</div>