config/routes.rb
Rails.application.routes.draw do

  get 'compras/confirmar', to: 'compras#confirmar'

  get 'compras/agregar', to: 'compras#agregar'

  post 'reportes/enviar', to: 'reportes#enviar'

  resources :answers

  resources :compras

  resources :logros 

  resources :reportes

  get 'main/default'
  root to: 'favors#index'

  

  devise_for :usuarios, :controllers => { registrations: 'registrations' }

  resources :usuarios, :only => [:index, :show]
 

  resources :favors
   get '/gauchadas', to: 'favors#index'
   get '/gauchadas/:id', to: 'favors#show'

  resources :comentarios do
    member do
      post 'comentar/:gau_id', :action => 'comentar', :as => 'comentar'
    end
  end

  resources :postulacions

  get '/elegiruser', to: 'postulacions#elegir_usuario'
  get '/finalizar_gauchada', to: 'favors#finalizar_gauchada'
  get '/gauchada_resuelta', to: 'favors#gauchada_resuelta'
  get '/gauchada_no_resuelta', to: 'favors#gauchada_no_resuelta'
end

app/models/favor.rb
class Favor < ActiveRecord::Base
	belongs_to :usuario

	default_scope -> { order("created_at desc") }
	scope :titulo, -> (titulo) { where("lower(titulo) like ?", "%#{titulo.downcase}%")}
  	scope :ubicacion, -> (ubicacion) { where ubicacion: ubicacion }

	has_many :postulacions, dependent: :destroy
	has_many :comentarios, dependent: :destroy

	def self.filtrar(resueltas,ubicacion,titulo)
		if ( resueltas.present? )
			if resueltas
				favores = Favor.all
			end
		else
			favores = Favor.where resuelta: false
		end
  		favores = favores.ubicacion(ubicacion) if ubicacion.present?
  		favores = favores.titulo(titulo) if titulo.present?
  		return favores

	end

	def tiene_elegido?
		postus = self.postulacions
		postus.each do |p|
			if p.elegido
				return true
			end
		end
		return false
	end

	def get_elegido
		p = self.postulacions.where(elegido: true)
		p.each do |pp|
			if pp.favor_id == self.id
				return pp.usuario_id
			end
			return 0
		end
	end

	def resolver
		self.resuelta = true
		self.postulacions.where(elegido: false).destroy_all
		user = Usuario.find(self.get_elegido)
		user.puntos = user.puntos + 1
		user.save
		self.save
	end
	def no_resolver
		self.resuelta = false
		user = Usuario.find(self.get_elegido)
		user.puntos = user.puntos - 1
		user.save
		Postulacion.where(favor_id: self.id, usuario_id: user.id).destroy_all
		self.save
	end
end

app/controllers/favors_controller.rb
class FavorsController < ApplicationController
	include ApplicationHelper
	before_filter :verificar_usuario, :only => [:show, :new, :create, :destroy, :update, :edit]


	def index
		@favores = Favor.filtrar(params[:resueltas], params[:ubicacion], params[:titulo])
	end

	# A list of the param names that can be used for filtering the Product list
	def filtro_params(params)
  		params.slice(:ubicacion)
	end

	def show
		@favor = Favor.find(params[:id])
		@comentarios = @favor.comentarios
		@comentario = Comentario.new
		@respuesta = Answer.new
	end
	def new
		if usuario_signed_in?
			if current_usuario.puntos > 0
			@favor = Favor.new
			else
				return redirect_to gauchadas_path, notice: "Para solicitar una gauchada debes tener puntos"
			end
		else
			return redirect_to gauchadas_path, notice: "Para solicitar una gauchada debes iniciar sesión"
		end
	end
	def create
		@fa=Favor.new(titulo: params[:favor][:titulo], descripcion: params[:favor][:descripcion], ubicacion: params[:favor][:ubicacion], foto: params[:favor][:foto], usuario_id: current_usuario.id)
		if @fa.foto == ""
			@fa.foto = "http://i.imgur.com/HBEa2Op.png"
		end
		@fa.resuelta = false;
		@fa.save
		u = current_usuario
		u.puntos = u.puntos - 1
		u.save
		redirect_to gauchadas_path, notice: 'Gauchada creada exitosamente'
	end

	def destroy
		@favor = Favor.find(params[:id])
		if (current_usuario.id == @favor.usuario_id && !@favor.resuelta)
			@favor.destroy
			redirect_to gauchadas_path, notice: "Gauchada Eliminada"
		else
			redirect_to gauchadas_path, alert: "No tienes permiso para realizar esta acción"
		end	
	end	

	def edit
	    if current_usuario.id == Favor.find(params[:id]).usuario_id
			@gauchada=Favor.find(params[:id])
			if @gauchada.resuelta
				redirect_to(root_path, alert: 'No puedes acceder a esa página.')
			end
		else
			redirect_to(root_path, alert: 'No puedes acceder a esa página.')
		end
	end
	def update
		@gauchada=Favor.find(params[:id])
		if params[:favor][:foto] == ""
			@gauchada.update(titulo: params[:favor][:titulo], descripcion: params[:favor][:descripcion], ubicacion: params[:favor][:ubicacion], foto: "http://i.imgur.com/HBEa2Op.png")
			redirect_to favor_path(:id => @gauchada.id), notice: 'Gauchada actualizada!'
		else
			@gauchada.update(titulo: params[:favor][:titulo], descripcion: params[:favor][:descripcion], ubicacion: params[:favor][:ubicacion], foto: params[:favor][:foto])
			redirect_to favor_path(:id => @gauchada.id), notice: 'Gauchada actualizada!'
		end
	end

	def finalizar_gauchada
		if Favor.find(params[:id]).tiene_elegido?
			@gauchada = Favor.find(params[:id])
		else
			redirect_to favor_path(:id => @gauchada.id), notice: 'Esta gauchada no tiene un candidato asignado por lo que no puede resolverse'
		end
	end

	def gauchada_resuelta
		g = Favor.find(params[:id])
		MyMailer.resolvio_gauchada(g).deliver_now
		g.resolver		
		redirect_to root_path, notice:'Gauchada resuelta! :D'		
	end

	def gauchada_no_resuelta
		g = Favor.find(params[:id])
		MyMailer.no_resolvio_gauchada(g).deliver_now
		g.no_resolver
		redirect_to root_path, notice:'La gauchada volvio al listado :('	
	end
end

app/views/favors/_borrarfiltros.erb
<td>
	<div style="margin-top: 17px; margin-left: -15px ;margin-right: 30px">
		<a href="<%= root_path %>" class="btn btn-danger">&times;</a>
	</div>
</td>

app/views/favors/_gauchadas.erb
<% @favores.each do |f| %>
	<% if f.resuelta %>
		<div class="border-gau-md-res" style="overflow: auto;">
	<% else %>
		<% if f.tiene_elegido? %>
		<div class="border-gau-md-pend" style="overflow: auto;">
		<% else %>
		<div class="border-gau-md" style="overflow: auto;">
		<% end %>
	<% end %>
			<table style="margin-left: 10px;">
			<tr>
			<td style="vertical-align: top">
				<div class="image-container" style="margin-top: 10px;">
					<%= image_tag f.foto, title:"FotoGau", class:"img-md"%>
				</div>
			</td>
			<td>
			<div style="margin-left: 30px; margin-top: 0px">
				<p style="font-size:17px; max-height: 60px; overflow: auto;"><%= f.titulo%></p>
				<% if !usuario_signed_in? %>
				<p style="font-style: italic; font-size: 12px; color: grey"> Creada el <%= f.created_at.strftime("%d/%m/%Y %H:%M") %> en <%= f.ubicacion %> por <%= Usuario.find(f.usuario_id).nombre.capitalize+" "+Usuario.find(f.usuario_id).apellido.capitalize %></p>
				<% else %>
				<p style="font-style: italic; font-size: 12px; color: grey"> Creada el <%= f.created_at.strftime("%d/%m/%Y %H:%M") %> en <%= f.ubicacion %> por <%= link_to Usuario.find(f.usuario_id).nombre.capitalize+" "+Usuario.find(f.usuario_id).apellido.capitalize, usuario_path(:id => f.usuario_id)%></p>
				<% end %>
			</div>
			</td>
			</tr>
			</table>
			<div style="float: right; margin-top: -13px">
					<% if usuario_signed_in? %>
					<% if (current_usuario.id == f.usuario_id) && !(f.resuelta)%>
						<%= link_to "Eliminar", f, method: :delete, data: {confirm: '¿Esta seguro de eliminar esta gauchada?'}, class: 'btn btn-danger btn-md' %>
					<% end%>
					<%= link_to "Ver Detalle", favor_path(:id => f.id), class: 'btn btn-warning btn-md' %>
					<% else %>
					<%= link_to "Ver Detalle", favor_path(:id => f.id), class: 'btn btn-default btn-md disabled' %>
					<% end %>
			</div>
	</div>
	<% end %>
	<% if @favores.count == 0 %>
		<p style="font-size: 24px; font-style: italic; color: grey; margin-left: 20px; margin-bottom: 20px"> No hay gauchadas para mostrar!</p>
	<% end %>

app/views/favors/edit.html.erb
		<div class="border-form-div">
		<h2> Editar Gauchada </h2>
		<%= form_for (@gauchada) do |f| %>
			<div class="field">
				<%= f.label :titulo, 'Titulo' %>
				<%= f.text_field :titulo, required: true, placeholder: 'Ingrese un titulo' %>
			</div>
			<div class="field">
				<%= f.label :descripcion, 'Descripción' %>
				<%= f.text_area :descripcion, required: true, placeholder: 'Indique de que trata...', class: "form-control", style: "margin-bottom: 15px; width: 92%" %>
			</div>
			<div class="field">
				<%= f.label :ubicacion, 'Ubicación' %>
				<%= f.select :ubicacion, opciones_para_ubicacion, required: true%>
			</div>
			<div class="field">
				<%= f.label :foto, 'Foto' %>
				<%= f.text_field :foto, placeholder: 'Por favor, introduzca el link de la foto'%>
			</div>
			<%= f.hidden_field :id, value: @gauchada.id%>
			<div class="actions">
		    <%= f.submit "Guardar", :class=>'btn btn-primary'%>
		    <%= link_to "Cancelar", gauchadas_path, :class =>'btn btn-default' %>
		  </div>
		 <% end %>
		</div>

app/views/favors/finalizar_gauchada.html.erb
<div class="border-list-div">
	<h2>Cierre de la Gauchada</h2>
	<hr>
	<% posts = @gauchada.postulacions%>
	<% postulacion_buscada = posts.find_by elegido: true %>
	<% nombre = Usuario.find(postulacion_buscada.usuario_id).nombre.capitalize%>
	<% apellido = Usuario.find(postulacion_buscada.usuario_id).apellido.capitalize%>
	<p>Usted esta a punto de finalizar la siguiente gauchada:</p>
	<div class="border-element-div" style="overflow: auto; width: 100%">
		<div class="row">
			<div class="col-md-1">
				<div class="image-container" style="margin-top: 10px; border: 3px solid #f1f1f1;">
					<%= image_tag @gauchada.foto, title:"FotoGau", class:"img-md"%>
				</div>
			</div>
			<div class="col-md-5">
				<div style="margin-left: 0px; margin-top: 30px">
					<p style="font-size:25px; max-height: 60px; overflow: auto;"><%= @gauchada.titulo%></p>
				</div>
			</div>
			<div class="col-md-6">
				<div style="margin-left: 0px; margin-top: 30px">
					<p style="font-size:25px; max-height: 60px; overflow: auto;">Candidato elegido: <%= link_to nombre+" "+apellido, usuario_path(:id => postulacion_buscada.usuario_id) %></p>
				</div>
			</div>
		</div>
	</div>
	<p> Por favor lea las siguientes aclaraciones:</p>
	<ul>
		<li> Al marcar la gauchada como <b>"Resuelta"</b>, esta se guardara en ese estado y el candidato elegido recibira <b>1 punto.</b></li>
		<li> Al marcar la gauchada como <b>"No Resuelta"</b>, la misma volvera al listado como si nunca hubiese elegido un postulante (mantendra postulaciones anteriores y recibira nuevas) y el candidato elegido perdera <b>1 punto.</b></li>
		<li> Una vez elegida una opcion, no podra volver atras.</li>
		<li> UnaGauchada deja en manos de los usuarios la verificacion de que una gauchada fue resuelta o no, y no provee herramientas en ese ambito. Por lo tanto, queda en responsabilidad del <b>solicitante</b> y del <b>candidato elegido</b> decidir si la gauchada fue bien resuelta o no.</li>
	</ul>
	<div style="margin-top: 20px; margin-bottom: 20px;">
		<%= link_to "Resuelta", gauchada_resuelta_path(:id => @gauchada.id), class:"btn btn-success btn-lg" %>
		<%= link_to "Sin Resolver", gauchada_no_resuelta_path(:id => @gauchada.id), class:"btn btn-danger btn-lg" %>
		<%= link_to 'Cancelar', @gauchada, class: 'btn btn-info btn-lg'%> 
	</div>
</div>

app/views/favors/gauchada_resuelta.html.erb
<%=hola%>

app/views/favors/index.html.erb
<% if !usuario_signed_in? %>
		<div class="alert alert-warning" role="alert"; style="width: 60%; margin-left: 20%;">
			<p style="text-align: center">
				Para ver el detalle de una gauchada debes
				<%= link_to "iniciar sesión", new_usuario_session_path%>
			</p>
		</div>
<%end%>

<div class="border-list-div">
	<h1>Listado de Gauchadas</h1>

	<div class="filtros-div" style="overflow: auto">
		<%= form_tag gauchadas_path, :method => 'get' do %>
		<table>
		<tr>
		<td>
		<div style="margin-right: 15px">
			<strong> Título: </strong>
			<br/>
			<%= text_field_tag :titulo, params[:titulo], placeholder: "Ingrese texto para buscar" %>
			</div>
		</td>
		<td>
		<td>
		<div style="margin-right: 15px">
			<strong> Ubicación: </strong>
			<br/>
			<div class="styled-select">
				<% text_field_tag :ubicacion, params[:ubicacion] %>
				<%= select_tag :ubicacion, options_for_select(opciones_para_ubicacion,params[:ubicacion]), prompt: "Seleccione una ubicación", :style => "height: 30px; border: 0px"%>
			</div>
			</div>
		</td>
		<td>
		<div style="margin-right: 15px">
			<table>
				<tr>
					<td style="padding-top: 13px">
						<%= check_box_tag :resueltas, true, params[:resueltas]=='true' %> 
					</td>
					<td style="padding-left: 5px; padding-top: 20px">
						<%= label_tag :resueltas, "Mostrar resueltas" %>
					</td>
				</tr>
			</table>
				
				
		</div>
		</td>
		<td>
		<div style="margin-top: 17px; margin-right: 30px">
				<%= submit_tag "Filtrar" , class: 'btn btn-default'%>
		</div>
		</td>
		<% if  (params[:resueltas].present? || params[:ubicacion].present? || params[:titulo].present?) %>
		<div id="borr"><%= render 'favors/borrarfiltros' %> </div>
		<% end %>
		</tr>
		</table>
		<% end %>
	</div>

	<div id="gauchs"><%= render 'favors/gauchadas' %> </div>
	

	<% if usuario_signed_in? %>
		<div style="padding-top: 30px; margin-bottom: -20px">
		<% if current_usuario.puntos > 0 %>
			<%= link_to "Pedir Gauchada", new_favor_path, class: 'btn btn-success btn-lg' %>
		<% else %>
			<%= link_to "No tienes puntos", new_favor_path, class: 'btn btn-default btn-lg disabled' %>
			<%= link_to "Tienda", compras_path, class: 'btn btn-success btn-lg' %>
		<% end %>
		</div>
	<% end %>
	<br>
</div>

app/views/favors/new.html.erb
<div class="border-form-div">
<h2> Crear Gauchada </h2>
<%= form_for (@favor) do |f| %>
	<div class="field">
		<%= f.label :titulo, 'Titulo' %>
		<%= f.text_field :titulo, required: true, placeholder: 'Ingrese un titulo' %>
	</div>
	<div class="field">
		<%= f.label :descripcion, 'Descripción' %>
		<br/>
		<%= f.text_area :descripcion, required: true, placeholder: 'Indique de que trata...', class: "form-control", style: "margin-bottom: 15px; width: 92%" %>
	</div>
	<div class="field">
		<%= f.label :ubicacion, 'Ubicación' %>
		<%= f.select :ubicacion, opciones_para_ubicacion, required: true%>
	</div>
	<div class="field">
		<%= f.label :foto, 'Foto' %>
		<%= f.text_field :foto, placeholder: 'Por favor, introduzca el link de la foto'%>
	</div>
	<div class="actions">
    <%= f.submit "Postear", :class=>'btn btn-primary'%>
    <%= link_to "Cancelar", gauchadas_path, :class =>'btn btn-default' %>
  </div>
 <% end %>
</div>

app/views/favors/show.html.erb
<% ape = Usuario.find(@favor.usuario_id).apellido.capitalize %> 
<% nom = Usuario.find(@favor.usuario_id).nombre.capitalize %> 
<% fech = @favor.created_at.strftime("%d/%m/%Y %H:%M") %>
<% ubic = @favor.ubicacion %>

<div class="border-list-div">
	<h2> Detalle de Gauchada </h2>	
	<% if @favor.resuelta %>
		<div class="border-element-div-res" style="overflow: auto;">
	<% else %>
		<% if @favor.tiene_elegido? %>
		<div class="border-element-div-pend" style="overflow: auto;">
		<% else %>
		<div class="border-element-div" style="overflow: auto; width: 100%">
		<% end %>
	<% end %>
		<table>
			<tr>
				<td style="vertical-align: top">
					<div class= "image-container-gau" style="margin-right: 25px; margin-top: 30px">
						<%= image_tag @favor.foto, title:"FotoGau", class:"img-xl"%>
					</div>
				</td>
				<td style="vertical-align: top; text-align: left;">
					<div style="display: inline-block;padding-right: 15px; margin-top: 10px">
						<h3 style="width: 400px"> <%= @favor.titulo %> </h3>
						<p><strong> Dueño: </strong> <%= link_to nom+" "+ape, usuario_path(:id => @favor.usuario_id) %></p>
						<p><strong> Fecha de creación: </strong> <%= @favor.created_at.strftime("%d/%m/%Y %H:%M") %></p>
						<p><strong> Ubicación: </strong> <%= @favor.ubicacion %> </p>			
						<p><strong> Descripción: </strong> </p>
						<p style="margin-left: 15px; max-width: 320px"> <i> <%= @favor.descripcion %> </i> </p>
					</div>
				</td>
			</tr>
		</table>
		<div style="float: right; margin-top: 15px; margin-bottom: -10px">
			<% if usuario_signed_in? %>
				<% if current_usuario.id != @favor.usuario_id %>
					<% if current_usuario.esta_postulado?(@favor)%>
						<% posts = @favor.postulacions%>
						<% postulacion_buscada = posts.find_by usuario_id: current_usuario.id %>
						<% if not @favor.resuelta %>
						<% if postulacion_buscada.elegido %>
							<%= link_to "Has sido elegido para resolver esta gauchada", "#{}", class: 'btn btn-default disabled' %>
							<%= link_to "Cancelar oferta", postulacion_buscada, method: :delete, data: {confirm: 'Atención! Fuiste seleccionado para resolver esta gauchada, si cancelas tu oferta perderás 1 punto!'}, class: 'btn btn-danger' %>
						<% else %>
							<%= link_to "Cancelar oferta", postulacion_buscada, method: :delete, data: {confirm: 'Seguro que deseas cancelar tu oferta? (Aún no has sido elegido para resolverla)'}, class: 'btn btn-danger' %>
						<% end %>
						<% else %>
							<%= link_to "Has resuelto esta gauchada", "#" , class: 'btn btn-default disabled' %>
						<% end %>
					<% else %>
						<% if not @favor.resuelta %>
						<% if !@favor.tiene_elegido? %>
							<a href="/postulacions/new?favor_id=<%=@favor.id%>", class="btn btn-success">Postularse</a>
						<% else %>
							<div class="btn btn-default disabled">No acepta candidatos</div>
						<% end %>
						<% else %>
							<%= link_to "Esta gauchada ha sido resuelta", "#" , class: 'btn btn-default disabled' %>
						<% end %>
					<% end %>
				<% else %>
					<% if (@favor.tiene_elegido?) && (!@favor.resuelta) %>
						<%= link_to "Finalizar", finalizar_gauchada_path(:id => @favor.id), class: 'btn btn-success' %>
					<% end %>
					<% if not @favor.resuelta %>
					<%= link_to "Editar", edit_favor_path(:id => @favor.id), class: 'btn btn-primary' %>
					<% else %>
						<%= link_to "Esta gauchada ha sido resuelta", "#" , class: 'btn btn-default disabled' %>
					<% end %>
				<% end %>
			<% end %>
		</div>

	</div>

	<div class="row" >
		<% if current_usuario.id == @favor.usuario_id %>
		<div class="col-md-6">
			<% else %>
			<div class="col-md-12">
				<% end %>
				<div id="seccion-comentarios" class="border-element-sm-div" style="overflow: hidden">
					<h3 style="width: 500px">Comentarios</h3>
						<div id="comentarios">
							<%= render @comentarios %>
						</div>
					<% if @comentarios.count <= 0 %>
						<p style="font-style: italic; color: grey; margin-left: 10px"> Aún no hay comentarios. Haz uno!</p>
					<% end %>
					<% if (usuario_signed_in?) && (!@favor.resuelta)%>
					<div style="overflow: auto">
						<%= render :partial => 'comentarios/form' %>
					</div>
					<% end %>
				</div>
			</div>
			<!-- ACA TERMINA COLUMNA COMENTARIOS -->
			<% if current_usuario.id == @favor.usuario_id %>
			<div class="col-md-6">
				<div class="border-element-sm-div" style="overflow: hidden">
					<h3 style="width: 500px">Postulantes</h3>
					<% if !@favor.resuelta %>
						<% if @favor.postulacions.count > 0 %>
							<% postulantes = @favor.postulacions%>
							<% postulantes.each do |p| %>
								<div class="border-gau-sm" style="overflow: auto">
										<b style="display: inline-block;"><%= link_to Usuario.find(p.usuario_id).nombre.capitalize+" "+Usuario.find(p.usuario_id).apellido.capitalize, usuario_path(:id => p.usuario_id)%></b>
										<i style="font-size: 10px; color: grey; display: inline-block;"> <%= p.created_at.strftime("%d/%m/%Y %H:%M") %> </i>
										<br/>
										<i style="display: inline-block;"> <%= p.descripcion %> </i>
										<div style="float: right">
										<% if @favor.tiene_elegido? %>
											<% elegido_id = @favor.get_elegido %>
											<% if p.usuario_id == elegido_id %>
												<%= link_to "Cancelar", p, method: :delete, data: {confirm: 'Seguro quieres cancelar la postulacion?'}, class:"btn btn-danger btn-xs"%>
											<% else %>
												<div class="btn btn-default btn-xs disabled">Aceptar</div>
											<% end %>
										<% else %>
											<%= link_to "Aceptar", p, class:"btn btn-success btn-xs"%>
										<% end %>
										</div>
								</div>
							<% end %>
						<% else %>
							<p style="font-style: italic; color: grey; margin-left: 10px"> Aún no tienes postulantes.</p>
						<% end %>
					<% else %>
						<%popostus = @favor.postulacions%>
						<% ppp = popostus.find_by elegido: true%>
						<div class="border-gau-sm" style="overflow: auto">
							<b style="display: inline-block;"><%= link_to Usuario.find(ppp.usuario_id).nombre.capitalize+" "+Usuario.find(ppp.usuario_id).apellido.capitalize, usuario_path(:id => ppp.usuario_id)%></b> resolvio esta gauchada.
						</div>
					<% end %>
				</div>
			</div>
			<% end %>
		</div>
		<%= link_to "Volver", root_path , class: 'btn btn-info btn-lg' %>
	</div>
