config/routes.rb
Rails.application.routes.draw do

  get 'compras/confirmar', to: 'compras#confirmar'

  get 'compras/agregar', to: 'compras#agregar'

  post 'reportes/enviar', to: 'reportes#enviar'

  resources :answers

  resources :compras

  resources :logros 

  resources :reportes

  get 'main/default'
  root to: 'favors#index'

  

  devise_for :usuarios, :controllers => { registrations: 'registrations' }

  resources :usuarios, :only => [:index, :show]
 

  resources :favors
   get '/gauchadas', to: 'favors#index'
   get '/gauchadas/:id', to: 'favors#show'

  resources :comentarios do
    member do
      post 'comentar/:gau_id', :action => 'comentar', :as => 'comentar'
    end
  end

  resources :postulacions

  get '/elegiruser', to: 'postulacions#elegir_usuario'
  get '/finalizar_gauchada', to: 'favors#finalizar_gauchada'
  get '/gauchada_resuelta', to: 'favors#gauchada_resuelta'
  get '/gauchada_no_resuelta', to: 'favors#gauchada_no_resuelta'
end

app/models/reporte.rb
class Reporte < ActiveRecord::Base
	default_scope -> { order("created_at desc") }
	has_many :usuarioreportes, dependent: :destroy
	belongs_to :usuario
	enum tipo: [ :de_usuarios, :de_ganancias ]
	enum tipodeusuarios: [ :mas_gauchadas_resueltas, :mas_gauchadas_pedidas , :mas_puntos]

end

app/controllers/reportes_controller.rb
class ReportesController < ApplicationController
	include ApplicationHelper
  	before_filter :verificar_admin

	def index
		@reportes = Reporte.all

	end

	def show
		@reporte = Reporte.find(params[:id])
	end

	def new
		@reporte=Reporte.new
	end

	def create
		@reporte=Reporte.new(titulo: params[:reporte][:titulo], tipo: params[:reporte][:tipo], fechainicial: params[:reporte][:fechainicial], fechafinal: params[:reporte][:fechafinal], cantidad: params[:reporte][:cantidad], tipodeusuarios: params[:reporte][:tipodeusuarios], usuario_id: current_usuario.id)
		if not @reporte.tipo == 'de_ganancias'
		usuarios = Usuario.all 
		usuarios.each do |u| 
			if @reporte.tipodeusuarios == 'mas_gauchadas_pedidas'
				pedidas = Favor.where(:usuario_id => u.id).count
				usuariopalrep = Usuarioreporte.new
				usuariopalrep.usuario_id = u.id
				usuariopalrep.cantidad = pedidas
			else
				if @reporte.tipodeusuarios == 'mas_gauchadas_resueltas'
					favores = Favor.where.not(:usuario_id => u.id).where(:resuelta => true)
					count = 0
				    favores.each do |f| 
						flag = false 
						f.postulacions.each do |p| 
							if p.usuario_id == u.id 
								flag = true 
								count = count+1
								break		
							end 
						end 
					end
					usuariopalrep = Usuarioreporte.new
					usuariopalrep.usuario_id = u.id
					usuariopalrep.cantidad = count
				else
					usuariopalrep = Usuarioreporte.new
					usuariopalrep.usuario_id = u.id
					usuariopalrep.cantidad = u.puntos
				end	
			end	
			@reporte.usuarioreportes << usuariopalrep
		end
		end
		if @reporte.tipo == 'de_ganancias' && @reporte.fechainicial >= @reporte.fechafinal
			redirect_to reportes_path, alert: 'Error en las fechas del reporte'
		else 
			@reporte.save
			if @reporte.cantidad.present? 
				if @reporte.usuarioreportes.count > @reporte.cantidad
					cantaborrar = @reporte.usuarioreportes.size - @reporte.cantidad
					@reporte.usuarioreportes.reverse_order.limit(cantaborrar).destroy_all
				end
			end
			redirect_to reporte_path(:id => @reporte.id), notice: 'Reporte creado exitosamente'
		end
	end

	def destroy 
		@reporte = Reporte.find(params[:id])
		@reporte.destroy
		redirect_to reportes_path, notice: "Reporte Eliminado"		
	end

	def enviar
		@reporte = Reporte.find(params[:id])
		MyMailer.reporte_mail(@reporte,current_usuario).deliver_now
		redirect_to reporte_path(:id => params[:id]), notice: 'El correo ha sido enviado'
	end
end

app/views/reportes/_reporte.html.erb
<h3> <%= @reporte.titulo %> </h3>
<p style="font-style: italic; font-size: 11px; color: grey; padding-bottom: 7px"> Reporte <%= @reporte.tipo.humanize.downcase %> creado el <%= @reporte.created_at.strftime("%d/%m/%Y %H:%M") %> por <%= link_to Usuario.find(@reporte.usuario_id).nombre.capitalize+" "+Usuario.find(@reporte.usuario_id).apellido.capitalize, usuario_path(:id => @reporte.usuario_id)%></p>
<% if @reporte.tipo == 'de_usuarios' %>
	<h4> Ranking de usuarios con <%= @reporte.tipodeusuarios.humanize.downcase %> </h4>
	<table class="table">
		<thead>
			<tr>
			<td> <strong> Nombre de usuario </strong> </td>
			<td> 
			<% if @reporte.tipodeusuarios == 'mas_gauchadas_pedidas' %>
				<strong> # Gauchadas pedidas </strong>
			<% else %>
				<% if @reporte.tipodeusuarios == 'mas_gauchadas_resueltas' %>
					<strong> # Gauchadas resueltas </strong>
				<% else %>
					<strong> Puntos </strong>
				<% end %>
			<% end %>
			</td>
			</tr>
		</thead>

		<% usuariosreporte = @reporte.usuarioreportes %>

		<tbody>
		<% usuariosreporte.each do |u| %>
		<tr>
			<td> <%= link_to Usuario.find(u.usuario_id).nombre.capitalize+" "+Usuario.find(u.usuario_id).apellido.capitalize, usuario_path(:id => u.id)%> </td>
			<td> <%= u.cantidad %> </td>
		</tr>
		<% end %>
		</tbody>
	</table>

<% else %>
	<h4> Reporte de ganancias entre <%= @reporte.fechainicial.strftime("%d/%m/%Y") %> y <%= @reporte.fechafinal.strftime("%d/%m/%Y") %></h4>
	<% compras = Compra.all %>
	<table class="table">
	<thead>
		<tr>
		<td> <strong> Comprador </strong> </td>
		<td> <strong> Cantidad de puntos </strong> </td>
		<td> <strong> Monto </strong> </td>
		</tr>
	</thead>

	<tbody>
		<% totalp = 0 %>
		<% totalm = 0 %>
		<% compras.each do |c| %>
			<% if c.created_at.to_date >= @reporte.fechainicial && c.created_at.to_date <= @reporte.fechafinal %>
				<% totalp = totalp + c.monto %>
				<tr>
					<td> <%= link_to Usuario.find(c.usuario_id).nombre.capitalize+" "+Usuario.find(c.usuario_id).apellido.capitalize, usuario_path(:id => c.usuario_id)%> </td>
					<td> <%= c.monto %> </td>
					<td>$<%= c.monto * 12 %> </td>
				</tr>
			<% end %>
		<% end %>	
	</tbody>

	<thead>
		<tr>
			<td></td>
			<td><strong> Total puntos </strong></td>
			<td><strong> Total monto </strong></td>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td></td>
			<td><%= totalp %></td>
			<td>$<%= totalp * 12 %></td>
		</tr>
	</tbody>	
	</table>
<% end %>

app/views/reportes/index.html.erb
<!--
	<div style="width: 60%; margin-left: 20%">< %= link_to "Crear logro", {:controller => "logros", :action => "new"}, class: 'btn btn-primary btn-block' %></div>
<br/>
-->
<div class="border-list-div" style="overflow: scroll;">
	<h1 style="width: 250px;"> Reportes </h1>
	<%= form_tag new_reporte_path, :method => 'get' do %>
	<table class="table">
		<thead>
			<tr>
				<th style="font-size:18px"> Titulo </th>
				<th style="font-size:18px"> Tipo </th>
				<th style="font-size:18px"> Creador </th>
				<th style="font-size:18px"> Opciones </th>
			</tr>
		</thead>
		<tbody>
			<% @reportes.each do |r| %>
			<tr>
				<td style="font-size:18px"> <%= r.titulo %> </td>
				<td style="font-size:18px"> <%= r.tipo.humanize %> </td>
				<td style="font-size:18px"> <%= link_to Usuario.find(r.usuario_id).nombre.capitalize+" "+Usuario.find(r.usuario_id).apellido.capitalize, usuario_path(:id => r.usuario_id)%> </td>
				<td style="font-size:18px; min-width: 160px;">
					<%= link_to "Ver", reporte_path(:id => r.id),  class: 'btn btn-warning btn-md' %>	
					<%= link_to "Eliminar", r, method: :delete, data: {confirm: '¿Esta seguro de eliminar este reporte?'}, class: 'btn btn-danger btn-md' %>		
				</td>
			</tr>
			<% end %>

			<% if @reportes.size == 0 %>
			<tr> <td colspan="3"> <i> <p style="font-size: 24px; font-style: italic; color: grey; margin-left: 10px; margin-bottom: 20px"> No hay reportes!</p> </i> </td> </tr>
			<% end %>
		</tbody>
		<thead>
			<tr>
				<th style="font-size:18px"> Nuevo reporte </th>
				<th style="font-size:18px"> </th>
				<th style="font-size:18px"> </th>
				<th style="font-size:18px"> </th>
			</tr>
		</thead>
		<tbody>
			<td style="font-size:18px">
			<%= text_field_tag :titulo,params[:titulo], placeholder: 'Ingrese titulo' %>
			</td>
			<td style="font-size:18px; padding-top: 10px;">
			<%= select_tag :tipo, options_for_select(Reporte.tipos.keys.map {|key| [key.humanize, key]},params[:tipo]) %> 
			</td>
			<td style="font-size:18px">
			</td>
			<td style="font-size:18px">
			<%= submit_tag 'Añadir', class: 'btn btn-success' %>
			</td>
		</tbody>
	</table>
	<% end %> <!-- del FORM -->
	<%= link_to "Volver", root_path , class: 'btn btn-info btn-lg' %>
</div>

app/views/reportes/new.html.erb
<div class="border-form-div">
<% if params[:tipo] == 'de_usuarios' %>
	<h2> Crear Reporte de Usuarios</h2>
<% else %>
	<h2> Crear Reporte de Ganancias</h2>
<% end %>
<%= form_for (@reporte) do |f| %>
	<%= f.hidden_field :tipo, value: params[:tipo]%>
	<div class="field">
		<%= f.label :titulo, 'Titulo' %>
		<%= f.text_field :titulo, required: true, placeholder: 'Ingrese un titulo', :value => params[:titulo] %>
	</div>
	<% if params[:tipo] == 'de_usuarios' %>
		<div class="field">
    		<%= f.label :tipodeusuarios, "Tipo de reporte" %><br />
			<%= f.select :tipodeusuarios, Reporte.tipodeusuarios.keys.map {|key| [key.humanize, key]} %>
		</div>
		<br />
		<div class="cantidad">
    		<%= f.label :cantidad, "Cantidad de usuarios incluidos" %><br />
			<%= f.select :cantidad, options_for_select([ ["Todos",nil],["3",3], ["5",5], ["10",10], ["50",50], ["100",100]], "Todos" )%>
		</div>
		<br />
	<% else %>
		<div>
    		<%= f.label :fechainicial, "Desde" %>
    		<br />
    		<%= f.date_field :fechainicial, min: "2016-11-01", max: Date.today.to_s, required:true %>
  		</div>
  		<br />
  		<div>
    		<%= f.label :fechafinal, "Hasta" %>
    		<br />
    		<%= f.date_field :fechafinal, min: "2016-11-01", max: Date.today.to_s, value: Date.today.to_s,required: true%>
  		</div>
  		<br />
	<% end %>

	<div class="actions">
    <%= f.submit "Generar", :class=>'btn btn-primary'%>
    <%= link_to "Cancelar", reportes_path, :class =>'btn btn-default' %>
  </div>
 <% end %>
</div>

app/views/reportes/show.html.erb
<div class="border-list-div">
 <h2> Información del reporte: </h2>
 <div class="border-element-div" style="overflow: auto">
 	<%= render 'reportes/reporte' %>
 </div>
 <%= link_to "Volver", reportes_path , class: 'btn btn-info btn-lg' %>
 <%= link_to "Enviar a mi correo", reportes_enviar_path(:id => @reporte.id), method: :post , class: 'btn btn-success btn-lg' %>
</div>