config/routes.rb
Rails.application.routes.draw do

  get 'compras/confirmar', to: 'compras#confirmar'

  get 'compras/agregar', to: 'compras#agregar'

  post 'reportes/enviar', to: 'reportes#enviar'

  resources :answers

  resources :compras

  resources :logros 

  resources :reportes

  get 'main/default'
  root to: 'favors#index'

  

  devise_for :usuarios, :controllers => { registrations: 'registrations' }

  resources :usuarios, :only => [:index, :show]
 

  resources :favors
   get '/gauchadas', to: 'favors#index'
   get '/gauchadas/:id', to: 'favors#show'

  resources :comentarios do
    member do
      post 'comentar/:gau_id', :action => 'comentar', :as => 'comentar'
    end
  end

  resources :postulacions

  get '/elegiruser', to: 'postulacions#elegir_usuario'
  get '/finalizar_gauchada', to: 'favors#finalizar_gauchada'
  get '/gauchada_resuelta', to: 'favors#gauchada_resuelta'
  get '/gauchada_no_resuelta', to: 'favors#gauchada_no_resuelta'
end

app/views/layouts/_header.html.erb
<div class="navbar navbarcustom navbar-fixed-top">
  <div class="navbar-header pull-left">
    <a class="navbar-brand" href="<%= root_path %>">
      <div style="display: inline-block;">
        <%= image_tag "logo_sm_w.png", title:"logo", style: "max-height: 40px; margin-top: -10px;"%>
      </div> Una Gauchada
    </a>
  </div>
  <div class="navbar-header boton pull-right">
      <% if usuario_signed_in? %>
      <% ape = current_usuario.apellido.capitalize %> 
      <% nom = current_usuario.nombre.capitalize %> 
      <div class="dropdown">
        <a class="dropdown-toggle" role="button" data-toggle="dropdown">
          <table class="boton" style="">
            <tr>
              <td style="width: 20px">
                <span class="caret" style="margin-left: 6px;margin-top: 40px"></span>
              </td>
              <td style="width: 50px">
                <div class="image-container-nav" style="">
                <% if current_usuario.foto.presence %>
                <%= image_tag current_usuario.foto, title:"FotoUsuario", class:"img-sm"%>
                <% else %>
                <%= image_tag "foto_stock.png", title:"FotoUsuario", class:"img-sm"%>
                <% end %>
                </div>  
              </td>
              <td style="width: 20px">
                
              </td>
            </tr>
          </table>  
        </a>
        <ul class="dropdown-menu dropdown-menu-right" style="margin-top: 0px;">
          <li><a href="<%= usuario_path(:id => current_usuario.id) %>">Mi perfil</a></li>
          <li><a href="<%= edit_usuario_registration_path %>">Editar mi perfil</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="<%= compras_path%>"> Comprar puntos</a></li>
          <% if usuario_es_admin? %>
          <li role="separator" class="divider"></li>
          <li><a href="<%= logros_path %>"><strong> Listado de Logros </strong></a></li>
          <li><a href="<%= reportes_path %>"><strong> Reportes </strong></a></li>
          <% end %>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Cerrar Sesion", destroy_usuario_session_path, :method => :delete %></li>
        </ul>
      </div>
      <% else %>
        <table>
          <tr>
              <div class= "link">
                <a class= "link-text" href="<%= new_usuario_session_path %>">Iniciar Sesión</a>
              </div>
          </tr>
          <tr>
              <div class= "link">
                <a class= "link-text" href="<%= new_usuario_registration_path %>">Registrate</a>
              </div>
          </tr>
        </table>
      <% end %>
  </div>
</div>

app/views/layouts/_logged_user_tag.html.erb
			<% ape = current_usuario.apellido.capitalize %> 
			<% nom = current_usuario.nombre.capitalize %> 
			<div style="float: left;overflow: auto; margin-right: 3px;">
				<div style="display: inline-block; text-align: right; overflow: auto;">
					<p style="line-height: 90%">Logeado como <%= nom %> <%= ape %></p>
					<p style="font-size: 10px; font-style: italic; color: grey;line-height: 50%;"> <%= current_usuario.email %> </p>

					<p style=" font-size: 12px;line-height: 100%"> Puntos: <%= current_usuario.puntos %> </p>
					<p style=" font-size: 12px;line-height: 90%"> <%= calc_logro(current_usuario.puntos) %> </p>	
							
				</div>
			</div>
			<div style="float: right;overflow: auto;">
				<div class="image-container-not-col" style="">
					<% if current_usuario.foto.presence %>
					<%= image_tag current_usuario.foto, title:"FotoUsuario", class:"img-md"%>
					<% else %>
					<%= image_tag "foto_stock.png", title:"FotoUsuario", class:"img-md"%>
					<% end %>
				</div>
			</div>

app/views/layouts/_user_tag.html.erb
			<!-- 
			Para usar esto:
			render :partial => 'layouts/user_tag', :locals => {:uid => id_de_usuario} 
			-->
			<% u = Usuario.find(uid) %>
			<% ape = u.apellido.capitalize %> 
			<% nom = u.nombre.capitalize %> 
			<div style="float: left;overflow: auto; margin-right: 3px;">
				<div style="display: inline-block; text-align: right;">
					<span style="margin-right: -3px"><%= nom %> <%= ape %></span>
					<br/>
					<span style="font-size: 10px; font-style: italic; color: grey;"> <%= u.email %> </span>
					<br/>
					<span style="margin-right: 1px; font-size: 12px"> Puntos: <%= u.puntos %> </span>
				</div>
			</div>
			<div style="float: right;overflow: auto;">
				<div class="image-container-not-col" style="">
					<% if u.foto.presence %>
					<% String fotoo = "" %>
					<% fotoo = u.foto+".jpg"%>
					<%= image_tag fotoo, title:"FotoUsuario", class:"listadogau"%>
					<% else %>
					<%= image_tag "foto_stock.png", title:"FotoUsuario", class:"listadogau"%>
					<% end %>
				</div>
			</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Una Gauchada</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body style="padding-top: 70px">
	<%= render 'layouts/header' %>
	<div class="container-fluid" style="padding-right: 80px; padding-left: 80px"> 
		<% if notice %>
				<div class="alert alert-warning alert-dismissable fade in" style="width: 60%; margin-left: 20%;text-align: center;" role="alert">
					<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
					<span class="notice" style="text-align: center;"><%= notice %></span>
				</div>
		<% end %>
		<% if alert %>
				<div class="alert alert-danger alert-dismissable fade in" style="width: 60%; margin-left: 20%;text-align: center;" role="alert">
					<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
					<span class="alert" style="text-align: center;"><%= alert %></span>
				</div>
		</div>	
		<% end %>
	<%= yield %>
	</div>
</body>
</html>

<script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover(); 
});
</script>